#Creating/ Reading dataframes:

In [0]:
import pandas as pd

1. Read uploaded csv in pyspark

In [0]:
df = spark.read.format("csv").option("header", "true").load("dbfs:/FileStore/shared_uploads/evashrestha99@gmail.com/Store_Sensors_data-1.csv")

In [0]:
df.show()

+----------+------+-------+---------+------------+-------+--------+
|      Date|  Hour|StoreNo|StoreName|EntranceName|InCount|OutCount|
+----------+------+-------+---------+------------+-------+--------+
|2021-12-11| 0:0:0|     30| My_Store|         001|      0|       0|
|2021-12-11| 0:0:0|     30| My_Store|         002|      0|       0|
|2021-12-11| 0:0:0|     30| My_Store|         003|      0|       0|
|2021-12-11| 0:0:0|     30| My_Store|         004|      0|       0|
|2021-12-11|0:15:0|     30| My_Store|         001|      0|       0|
|2021-12-11|0:15:0|     30| My_Store|         002|      0|       0|
|2021-12-11|0:15:0|     30| My_Store|         003|      0|       0|
|2021-12-11|0:15:0|     30| My_Store|         004|      0|       0|
|2021-12-11|0:30:0|     30| My_Store|         001|      0|       0|
|2021-12-11|0:30:0|     30| My_Store|         002|      0|       0|
|2021-12-11|0:30:0|     30| My_Store|         003|      0|       0|
|2021-12-11|0:30:0|     30| My_Store|         004|      0|       0|
|2021-12-11|0:45:0|     30| My_Store|         001|      0|       0|
|2021-12-11|0:45:0|     30| My_Store|         002|      0|       0|
|2021-12-11|0:45:0|     30| My_Store|         003|      0|       0|
|2021-12-11|0:45:0|     30| My_Store|         004|      0|       0|
|2021-12-11| 1:0:0|     30| My_Store|         001|      0|       0|
|2021-12-11| 1:0:0|     30| My_Store|         002|      0|       0|
|2021-12-11| 1:0:0|     30| My_Store|         003|      0|       0|
|2021-12-11| 1:0:0|     30| My_Store|         004|      0|       0|
+----------+------+-------+---------+------------+-------+--------+
only showing top 20 rows

2. Read uploaded xlsx file in pyspark

In [0]:
df_excel = spark.read.format("com.crealytics.spark.excel").option("header", "true").load("dbfs:/FileStore/shared_uploads/evashrestha99@gmail.com/sensor.xlsx")

In [0]:
df_excel.show()

+---------+---------+--------+
|StoreCode|StoreName|Entrance|
+---------+---------+--------+
|       30| My_Store|       1|
|       30| My_Store|       2|
|       30| My_Store|       3|
|       30| My_Store|       4|
|       30| My_Store|       1|
|       30| My_Store|       2|
|       30| My_Store|       3|
|       30| My_Store|       4|
|       30| My_Store|       1|
|       30| My_Store|       2|
|       30| My_Store|       3|
|       30| My_Store|       4|
|       30| My_Store|       1|
|       30| My_Store|       2|
|       30| My_Store|       3|
|       30| My_Store|       4|
|       30| My_Store|       1|
|       30| My_Store|       2|
|       30| My_Store|       3|
|       30| My_Store|       4|
+---------+---------+--------+
only showing top 20 rows

3. Create pandas dataframe and convert it to PySpark

In [0]:
data = {
    'Name': ['Eva', 'Den', 'Sanj', 'Ar','Bij'],
    'Age': [22, 23, 24, 25, 26],
    'Location': ['Ktm', 'Pokhara', 'Chitwan', 'Lumbini','Biratnagar']
}
df = pd.DataFrame(data)

In [0]:
df_spark = spark.createDataFrame(df)

In [0]:
df_spark.show()

+----+---+----------+
|Name|Age|  Location|
+----+---+----------+
| Eva| 22|       Ktm|
| Den| 23|   Pokhara|
|Sanj| 24|   Chitwan|
|  Ar| 25|   Lumbini|
| Bij| 26|Biratnagar|
+----+---+----------+

Converting spark dataframe to pandas

In [0]:
df_pandas = df_spark.toPandas()

In [0]:
df_pandas.head()

,Name,Age,Location
0,Eva,22,Ktm
1,Den,23,Pokhara
2,Sanj,24,Chitwan
3,Ar,25,Lumbini
4,Bij,26,Biratnagar